---
repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: yc-ave-apps
  url: {{ requiredEnv "CI_REGISTRY" }}/{{ requiredEnv "CI_REPOSITORY" }}
  oci: true
  username: {{ requiredEnv "CI_REGISTRY_USER" }}
  password: {{ requiredEnv "CI_REGISTRY_PASSWORD" }}

helmDefaults:
  verify: false
  wait: true
  waitForJobs: true
  timeout: 600
  recreatePods: false
  atomic: true
  cleanupOnFail: true
  force: false
  tls: false
  historyMax: 10
  createNamespace: false
  devel: false
  skipDeps: false
  
releases:
  - name: {{ requiredEnv "CI_PROJECT_NAME" }}
    namespace: {{ requiredEnv "KUBE_NAMESPACE" }}
    chart: {{ requiredEnv "CI_HELM_CHART" }}
    values:
      - {{ requiredEnv "CI_PROJECT_DIR" }}/{{ requiredEnv "CI_ENVIRONMENT_SLUG" }}-generated.yaml
      - image:
          repository: {{ requiredEnv "CI_REGISTRY" }}/{{ requiredEnv "CI_REPOSITORY" }}/{{ requiredEnv "CI_PROJECT_NAME" }}
          tag: {{ requiredEnv "CI_ENVIRONMENT_SLUG"}}-{{ requiredEnv "CI_PIPELINE_IID"}}
